### ISSUE TITLE
Can't read mobileraker.conf in docker

### ISSUE THREAD

**Issue by ColdBeer72** [Clon1998/mobileraker_companion#104]
I defined my compose yml file for Mobileraker (using OpenMediaVault as host), as expected:

```yaml
services:
  mobileraker_companion:
    container_name: mobileraker
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    image: ghcr.io/clon1998/mobileraker_companion:latest
    volumes:
      - CHANGE_TO_COMPOSE_DATA_PATH/mobileraker/mobileraker.conf:/opt/printer_data/config/mobileraker.conf
      - /etc/hosts:/etc/hosts:ro
    restart: unless-stopped
```
But when I start it, these lines appears in log (just few starting lines):
```log
mobileraker  | 2024-12-03 22:21:37 root INFO Logging to file: /tmp/mobileraker.log
m`obileraker  | 2024-12-03 22:21:37 root INFO MobilerakerCompanion version: ?
mobileraker  | 2024-12-03 22:21:37 root INFO Checking if passed config exists: printer_data/config/mobileraker.conf
mobileraker  | 2024-12-03 22:21:37 root INFO Found configuration file at: /opt/printer_data/config/mobileraker.conf
mobileraker  | 2024-12-03 22:21:37 root INFO Read 1 printer config sections
mobileraker  | 2024-12-03 22:21:37 root INFO Main section read, language:"en", timezone:"CET", eta_format:"%d.%m.%Y, %H:%M:%S", include_snapshot:"True"
mobileraker  | 2024-12-03 22:21:37 py.warnings WARNING /opt/mobileraker/mobileraker.py:44: DeprecationWarning: There is no current event loop
mobileraker  |   event_loop = asyncio.get_event_loop()
mobileraker  | 
mobileraker  | 2024-12-03 22:21:37 mobileraker._Default INFO MobilerakerCompanion client created for _Default, it will ignore the following sensors: []
mobileraker  | 2024-12-03 22:21:37 mobileraker._Default.jrpc INFO Trying to connect to: ws://127.0.0.1:7125/websocket api key <NO API KEY>
mobileraker  | 2024-12-03 22:21:37 websockets.client INFO ! connect failed; reconnecting in 0.6 seconds
```
The config file defined in the yaml contains "language: es", correct moonraker hosts, and other things, so it's like if docker is trying to find the config file in another place. In fact, it generate a "Volume" in another place (like `'/var/lib/docker/volumes/508737591f2115acdf2dcad618bfeefc16a7997ee66d6765047cc82b4de4ce67/_data`' with a mobileraker.conf (0 bytes) inside.

If I edit and change that 0 bytes file with the contents of mine, mobileraker doesn't detect the changes, so it's never configured.
 
---
If I change the volumes to:
```yaml
      volumes:
      - CHANGE_TO_COMPOSE_DATA_PATH/mobileraker/config:/opt/printer_data/config
      - /etc/hosts:/etc/hosts:ro
```
Then log changes but can't find the configuration and says it can't find the configuration file.

---
After some more tests later, it seems as mobileraker (inside the dockerized vm) is not reading that file, or can't find it, or is reding another file.
